#!/usr/bin/bash

articleyaml="/scripts/article.yaml"

if [[ $# -ne 2 ]]; then
	echo -e "command -p <filename>: Publish an article (ask for category preferences(e.g., 2,1 for Cinema and Sports), it should be reflected in public directory, update the YAML with the changes, and change permissions for users to view it).\n
command -a <filename>: Archive an article (remove symlink from public, revoke permissions, update YAML).\n
command -d <filename>: Delete an article (remove every trace of the article deleted)\n
command -e <filename>: Edit an article's categories (interactive menu to select new category order, update YAML)."
	exit 1
fi

if [[ "$EUID" -ne 0 ]]; then
	exec sudo "$0" "$1" "$2"
fi

touch "$articleyaml"

flag=$1
filename=$(realpath "$2")

askpref(){
	categories=("Sports" "Cinema" "Technology" "Travel" "Food" "Lifestyle" "Finance")
	order=()
	while [[ ${#categories[@]} -gt ${#order[@]}  ]]; do
		echo -e "\nChoose a Category"
		counter=1
		for i in "${categories[@]}"; do
			echo $counter\) $i
			counter=$((counter + 1))
		done;
		echo -e "8) Reset\n0)Submit"
		echo "current order: ${order[*]}"
		read input
		counter=$(($counter - 1))
		
		if [[ " ${order[*]} " =~ " $input " ]]; then
			echo -e "already chosen\n"
			continue
		fi

		if [[ "$input" =~ ^[1-$counter]$ ]]; then
			order+=("$input")
		elif [[ "$input" == "8" ]]; then
			categories=("Sports" "Cinema" "Technology" "Travel" "Food" "Lifestyle" "Finance")
			order=()
		elif [[ "$input" == "0" ]]; then
			order=$(IFS=, ; echo "${order[*]}")
			break
		else
			echo "wrong input try again"
		fi
	done;
}
	
if [[ $flag == "-p" ]]; then
	if [[ -e $filename && ! -L "/home/authors/$SUDO_USER/public/$(basename "$filename")" ]]; then
		yq -i 'del(.blogs[] | select(.file_name == "'"$filename"'"))' /home/authors/$SUDO_USER/blogs.yaml
		read_count=$(yq '(.blogs[] | select(.file_name == "'"$filename"'")).read_count' "$articleyaml")
		if [[ "$read_count" == "" ]]; then 
			read_count=0 
		fi
		yq -i 'del(.blogs[] | select(.file_name == "'"$filename"'"))' "$articleyaml"
	        askpref
	        touch /home/authors/$SUDO_USER/blogs.yaml
		chown $SUDO_USER /home/authors/$SUDO_USER/blogs.yaml
		ln -s "$filename" "/home/authors/$SUDO_USER/public/$(basename "$filename")"
		
		setfacl -m g:g_user:r-x "$filename"
		setfacl -m g:g_user:--x "/home/authors/$SUDO_USER/blogs"
		setfacl -m g:g_user:--x "/home/authors/$SUDO_USER"
		
		setfacl -m g:g_mod:rwx "$filename"
		setfacl -m g:g_mod:--x "/home/authors/$SUDO_USER"
		setfacl -m g:g_mod:--x "/home/authors/$SUDO_USER/blogs"
		
		yq -i '.blogs += [{"file_name": "'"$filename"'", "publish_status": true, "cat_order": ['"$order"'], "mod_comments": ""}]' /home/authors/$SUDO_USER/blogs.yaml
		echo Document published
		yq -i '.blogs += [{"file_name": "'"$filename"'", "publish_status": true, "cat_order": ['"$order"'], "author": "'"$SUDO_USER"'", "read_count": '"$read_count"'}]' "$articleyaml"
	else
		echo file does not exist or is already published
	fi
elif [[ $flag == "-a" ]]; then
	if [[ -e $filename && -L "/home/authors/$SUDO_USER/public/$(basename "$filename")" ]]; then
                rm "/home/authors/$SUDO_USER/public/$(basename "$filename")"
		setfacl -m g:g_user:--x "$filename"
                setfacl -m g:g_mod:--x "$filename"
		yq -i '(.blogs[] | select(.file_name == "'"$filename"'")).publish_status= false' /home/authors/$SUDO_USER/blogs.yaml
		echo Document archived
	else
                echo file does not exist or is not published
        fi
elif [[ $flag == "-d" ]]; then
	if [[ -e $filename ]]; then
		rm $filename
		symlink="/home/authors/$SUDO_USER/public/$(basename "$filename")"
		if [[ -L "$symlink" ]]; then
			rm "/home/authors/$SUDO_USER/public/$(basename "$filename")"
		fi
		yq -i 'del(.blogs[] | select(.file_name == "'"$filename"'"))' /home/authors/$SUDO_USER/blogs.yaml
		yq -i '(.blogs[] | select(.file_name == "'"$filename"'")).publish_status= false' "$articleyaml"
		echo Document deleted
	else
		echo file does not exist
	fi
elif [[ $flag == "-e" ]]; then
	if [[ -e $filename && -L "/home/authors/$SUDO_USER/public/$(basename "$filename")" ]]; then
		askpref
		yq -i '(.blogs[] | select(.file_name == "'"$filename"'")).cat_order= ['"$order"']' /home/authors/$SUDO_USER/blogs.yaml
	else
		echo file does not exist or is not published
	fi
else
	echo wrong input please try again
fi

